version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-broker
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"

  celery_worker:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    command: celery -A src.app.core.celery_config worker --loglevel=INFO
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0