version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task_manager_db
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis-broker
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+asyncpg://task_user:task_password@postgres:5432/task_manager
    ports:
      - "8000:8000"

  celery_worker:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    command: celery -A src.app.core.celery_config worker --loglevel=INFO
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+asyncpg://task_user:task_password@postgres:5432/task_manager

volumes:
  postgres_data: